/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author thismac
 */
public class addJob extends javax.swing.JPanel {

    /**
     * Creates new form addJob
     */
    public addJob() {
        initComponents();
        Mode.addItem("OnSite");
        Mode.addItem("Remote");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        Title = new javax.swing.JTextField();
        Description = new javax.swing.JTextArea();
        Location = new javax.swing.JTextField();
        Salary = new javax.swing.JFormattedTextField();
        Mode = new java.awt.Choice();

        Title.setForeground(java.awt.Color.gray);
        Title.setText("Job Title");
        Title.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TitleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TitleFocusLost(evt);
            }
        });

        Description.setColumns(20);
        Description.setForeground(java.awt.Color.gray);
        Description.setRows(5);
        Description.setText("Job Description, Experience and skills");
        Description.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DescriptionFocusLost(evt);
            }
        });

        Location.setForeground(java.awt.Color.gray);
        Location.setText("Location");
        Location.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LocationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LocationFocusLost(evt);
            }
        });

        Salary.setForeground(java.awt.Color.gray);
        Salary.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        Salary.setText("Salary");
        Salary.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SalaryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SalaryFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }

    private void TitleFocusGained(java.awt.event.FocusEvent evt) {
        if(Title.getText().equals("Job Title")){
            Title.setForeground(Color.BLACK);
            Title.setText("");
        }
    }

    private void TitleFocusLost(java.awt.event.FocusEvent evt) {
            Title.setForeground(Color.GRAY);
            Title.setText("Job Title");
        }
    }/

    private void DescriptionFocusGained(java.awt.event.FocusEvent evt) {
        if(Description.getText().equals("Job Description, Experience and skills")){
            Description.setForeground(Color.black);
            Description.setText("");
        }
    }

    private void DescriptionFocusLost(java.awt.event.FocusEvent evt) {
        if(Description.getText().isEmpty()){
            Description.setForeground(Color.gray);
            Description.setText("Job Description, Experience and skills");
        }
    }

    private void LocationFocusGained(java.awt.event.FocusEvent evt) {
        if(Location.getText().equals("Location")){
            Location.setForeground(Color.black);
            Location.setText("");
        }
    }

    private void LocationFocusLost(java.awt.event.FocusEvent evt) {
        if(Location.getText().isEmpty()){
            Location.setForeground(Color.gray);
            Location.setText("Location");
        }
    }

    private void SalaryFocusGained(java.awt.event.FocusEvent evt) {
        if(Salary.getText().equals("Salary")){
            Salary.setForeground(Color.black);
            Salary.setText("");
        }
    }

    private void SalaryFocusLost(java.awt.event.FocusEvent evt) {
        if(Salary.getText().isEmpty()){
            Salary.setForeground(Color.gray);
            Salary.setText("Salary");
        }
    }


 
    private javax.swing.JTextArea Description;
    private javax.swing.JTextField Lzocation;
    private java.awt.Choice Mode;
    private javax.swing.JFormattedTextField Salary;
    private javax.swing.JTextField Title;
    
    public String getTitle(){return Title.getText();}
    public String getDescription(){return Description.getText();}
    public String getMode(){return Mode.getSelectedItem();}
    public String getJobLocation(){return Location.getText();}
    public String getSalary(){return Salary.getText();}    

}
