/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.logInController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.border.LineBorder;

/**
 *
 * @author thismac
 */
public class Registration extends javax.swing.JFrame {
     String role = "seeker";
    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        RegisterLabel = new javax.swing.JLabel();
        cmpBtn = new javax.swing.JLabel();
        seekerBtn = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        uName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        rePass = new javax.swing.JPasswordField();
        submitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(161, 196, 247));
        jPanel1.setPreferredSize(new java.awt.Dimension(1087, 655));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Logo.png"))); // NOI18N
        Logo.setText("jLabel1");

        RegisterLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        RegisterLabel.setText("Register");

        cmpBtn.setBackground(new java.awt.Color(153, 204, 0));
        cmpBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmpBtn.setForeground(new java.awt.Color(204, 204, 204));
        cmpBtn.setText("Company");
        cmpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmpBtnMouseClicked(evt);
            }
        });

        seekerBtn.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        seekerBtn.setText("Seeker");
        seekerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seekerBtnMouseClicked(evt);
            }
        });

        name.setForeground(new java.awt.Color(204, 204, 204));
        name.setText("Enter your name");
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        uName.setForeground(new java.awt.Color(204, 204, 204));
        uName.setText("Enter username");
        uName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                uNameFocusLost(evt);
            }
        });
        uName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameActionPerformed(evt);
            }
        });

        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setText("e-mail");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        number.setForeground(new java.awt.Color(204, 204, 204));
        number.setText("Number");
        number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberFocusLost(evt);
            }
        });
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });

        address.setForeground(new java.awt.Color(204, 204, 204));
        address.setText("Address");
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        pass.setForeground(new java.awt.Color(204, 204, 204));
        pass.setText("password");
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });

        rePass.setForeground(new java.awt.Color(204, 204, 204));
        rePass.setText("re-password");
        rePass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rePassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rePassFocusLost(evt);
            }
        });
        rePass.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                rePassInputMethodTextChanged(evt);
            }
        });
        rePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rePassActionPerformed(evt);
            }
        });

        submitBtn.setBackground(new java.awt.Color(34, 35, 205));
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Register");
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel1.setText("Already have account?");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Login");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uName, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(number, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(rePass, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seekerBtn)
                                .addGap(18, 18, 18)
                                .addComponent(cmpBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(406, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RegisterLabel)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmpBtn)
                    .addComponent(seekerBtn))
                .addGap(31, 31, 31)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rePass, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                seekerBtn.requestFocusInWindow();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rePassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rePassActionPerformed

    private void rePassInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_rePassInputMethodTextChanged
        // TODO add your handling code here:
        if(pass.getText().equals(rePass.getText())){
            rePass.setBorder(pass.getBorder());
        }
    }//GEN-LAST:event_rePassInputMethodTextChanged

    private void rePassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rePassFocusLost
        // TODO add your handling code here:
        if(rePass.getText().isEmpty()){
            rePass.setForeground(Color.gray);
            rePass.setText("re-password");
            rePass.setEchoChar((char)0);
        }
        if(! pass.getText().equals(rePass.getText())){
            rePass.setBorder(new LineBorder(Color.RED));
        }else{
            rePass.setBorder(pass.getBorder());
        }
    }//GEN-LAST:event_rePassFocusLost

    private void rePassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rePassFocusGained
        // TODO add your handling code here:
        if(rePass.getText().equals("re-password")){
            rePass.setForeground(Color.BLACK);
            rePass.setText("");
            rePass.setEchoChar('*');
        }
    }//GEN-LAST:event_rePassFocusGained

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
        // TODO add your handling code here:
        if(pass.getText().isEmpty()){
            pass.setForeground(Color.gray);
            pass.setText("password");
            pass.setEchoChar((char)0);
        }
    }//GEN-LAST:event_passFocusLost

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        // TODO add your handling code here:
        if(pass.getText().equals("password")){
            pass.setForeground(Color.BLACK);
            pass.setText("");
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_passFocusGained

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        // TODO add your handling code here:
        if(address.getText().isEmpty()){
            address.setText("Address");
            address.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_addressFocusLost

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        // TODO add your handling code here:
        if(address.getText().equals("Address")){
            address.setText("");
            address.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_addressFocusGained

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void numberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFocusLost
        // TODO add your handling code here:
        if(number.getText().isEmpty()){
            number.setText("Number");
            number.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_numberFocusLost

    private void numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFocusGained
        // TODO add your handling code here:
        if(number.getText().equals("Number")){
            number.setText("");
            number.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_numberFocusGained

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if(email.getText().isEmpty()){
            email.setText("e-mail");
            email.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_emailFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("e-mail")){
            email.setText("");
            email.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_emailFocusGained

    private void uNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameActionPerformed

    private void uNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uNameFocusLost
        // TODO add your handling code here:
        if(uName.getText().isEmpty()){
            uName.setText("Enter username");
            uName.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_uNameFocusLost

    private void uNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uNameFocusGained
        // TODO add your handling code here:
        if(uName.getText().equals("Enter username")){
            uName.setText("");
            uName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_uNameFocusGained

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        if(name.getText().isEmpty()){
            name.setForeground(Color.GRAY);
            if(role.equals("company")){
                name.setText("Enter company name");
            }
            else if(role.equals("seeker")){
                name.setText("Enter your name");
            }
        }
    }//GEN-LAST:event_nameFocusLost

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        if((name.getText().equals("Enter your name") && role.equals("seeker")) || (name.getText().equals("Enter company name") && role.equals("company"))){
            name.setForeground(Color.BLACK);
            name.setText("");
        }
    }//GEN-LAST:event_nameFocusGained

    private void seekerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seekerBtnMouseClicked
        seekerBtn.setFont(new Font("Arial", Font.BOLD, 22));
        seekerBtn.setForeground(Color.BLACK);
        cmpBtn.setFont(new Font("Arial", Font.PLAIN, 18));
        cmpBtn.setForeground(Color.GRAY);
        role = "seeker";
        name.setText("Enter your name");

    }//GEN-LAST:event_seekerBtnMouseClicked

    private void cmpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmpBtnMouseClicked

        cmpBtn.setFont(new Font("Arial", Font.BOLD, 22));
        cmpBtn.setForeground(Color.BLACK);
        seekerBtn.setFont(new Font("Arial", Font.PLAIN, 18));
        seekerBtn.setForeground(Color.GRAY);
        role = "company";
        name.setText("Enter company name");

    }//GEN-LAST:event_cmpBtnMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Login registerForm = new Login();
        logInController c = new logInController(registerForm);
        c.open();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnMouseClicked
    
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JTextField address;
    private javax.swing.JLabel cmpBtn;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField rePass;
    private javax.swing.JLabel seekerBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField uName;
    // End of variables declaration//GEN-END:variables

    public void addAddUserListener(ActionListener listener) {
        submitBtn.addActionListener(listener);
    }
    
    public String getName() {
    String text = name.getText().trim();
    return text.isEmpty() || text.equals("Enter your name") || text.equals("Enter company name") ? "" : text;
    }

    public String getuName() {
        String text = uName.getText().trim();
        return text.isEmpty() || text.equals("Enter username") ? "" : text;
    }

    public String getEmail() {
        String text = email.getText().trim();
        return text.isEmpty() || text.equals("e-mail") ? "" : text;
    }

    public String getNumber() {
        String text = number.getText().trim();
        return text.isEmpty() || text.equals("Number") ? "" : text;
    }

    public String getAddress() {
        String text = address.getText().trim();
        return text.isEmpty() || text.equals("Address") ? "" : text;
    }

    public String getPassword() {
        String password = pass.getText().equals("password") ? "" : pass.getText().trim();
        String rePassword = rePass.getText().equals("re-password") ? "" : rePass.getText().trim();
        return password.equals(rePassword) ? password : "mismatch";
    }

    public String getRole() {
        return role;
    }
    
}
